<div class="criar">
    <form action="/criarpostagem" enctype="multipart/form-data" method="post">
        <div class="criacao">
            <div class="fotoperfil"></div>
            <textarea placeholder="Sobre oque você quer falar hoje?" required name="texto" id="conteudo" cols="30" rows="10"></textarea>
        </div>
        <div id="postagem_template"></div>
        <ul>
            <li id="midia_bt"><input id="image" name="imagem" accept="image/*" type="file"></li>
            <li id="privacidade_bt">
                <select name="privacidade" id="">
                    <option value="publica">Publico</option>
                    <option value="privada">Privado</option>
                </select>
            </li>

            <li><input id="postar_bt" type="submit" value="Postar"></li>
        </ul>
    </form>

    <script>
        document.getElementById('image').addEventListener('change', function(event) {
            if (!document.getElementById('imagemtemplate')) {
                const file = event.target.files[0];

                if (file) {
                    const reader = new FileReader();

                    reader.onload = function(e) {
                        const img = document.createElement('img');
                        img.src = e.target.result;
                        img.alt = 'Uploaded Image';
                        img.style.maxWidth = '100%';
                        img.id = 'imagemtemplate';

                        const postagemTemplate = document.getElementById('postagem_template');
                        postagemTemplate.appendChild(img);
                    };

                    reader.readAsDataURL(file);
                }

            } else {
                const file = event.target.files[0]; // Adicionando essa linha
                if (file) { // Verificação adicional para segurança
                    const reader = new FileReader();

                    reader.onload = function(e) {
                        const img = document.getElementById('imagemtemplate');
                        img.src = e.target.result;
                    };

                    reader.readAsDataURL(file); // Chamando o método aqui
                }
            }
        });
    </script>
</div>