<div class="criar">
    <div class="criacao">
        <div class="fotoperfil"></div>
        <textarea placeholder="Sobre oque você quer falar hoje?" name="" id="" cols="30" rows="10"></textarea>
    </div>
    <ul>
        <li id="midia_bt"><input accept="image/*" type="file"></li>
        <li id="privacidade_bt">
            <select name="" id="">
                <option value="0">Publico alvo</option>
                <option value="1">Meu perfil</option>
            </select>
        </li>

        <li id="postar_bt">Postar</li>
    </ul>
</div>