<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redefinição de Senha - My Friend Circle</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #eafaf1;
            /* Verde claro */
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: auto;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            text-align: center;
        }

        h1 {
            color: #4CAF50;
            /* Verde mais escuro */
        }

        .btn {
            background-color: #007BFF;
            /* Azul escuro */
            color: white;
            padding: 15px 25px;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin-top: 20px;
        }

        .alert {
            color: red;
            /* Vermelho para o alerta */
            font-size: 14px;
            margin-top: 15px;
        }

        #textcolor {
            color: white;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>My Friend Circle</h1>
        <p>Você recebeu esta mensagem porque solicitou a redefinição da sua senha.</p>
        <p>Clique no botão abaixo para redefinir sua senha:</p>
        <a href="http://localhost:8080/recuperarsenha?token=<?php  echo $_SESSION['token'] ?>" id="textcolor" class="btn">Redefinir Senha</a>
        <p class="alert">Se você não pediu isso, verifique suas configurações de segurança.</p>
    </div>
</body>

</html>