<div class="perfil_info">
    <div class="outbar"></div>
    <div class="fotoperfil"></div>
    <h1> <a class="nomeperfil" href="/usuarios"> <?php $this->show('nome') ?> </a> </h1>
    <p>Faça uma breve descrição sobre você</p>
    <form action="" method="post">
        <input type="button" value="Solicitar conexão">
    </form>
</div>

<div class="exibir_conteudos">
    <div class="conteudo">
        <div class="informacoes">
            <div class="fotoperfil"></div>
            <div class="s2">
                <a href="#"> <?php $this->show('nome') ?> </a>
                <p>sobre mim</p>
            </div>
            <div class="s3">
                <button>•••</button>
            </div>
        </div>
        <p class="descricao"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas velit
            praesentium quae dolorum nesciunt libero similique rerum eligendi! Neque similique ut
            nesciunt sequi sed, voluptatibus suscipit corporis. Voluptates, harum voluptatem.</p>
        <img src="../img/teste.png" alt="Conteudo se tiver">
        <div class="acoes">
            <button><span class="material-symbols-outlined">
                    thumb_up
                </span> Curtir</button>
            <button><span class="material-symbols-outlined">
                    comment
                </span> Comentar</button>
        </div>
    </div>
</div>