<?php 
foreach ($temp as $key => $value) { ?>
    <div class="conteudo">
        <div class="informacoes">
            <img src="../img/<?php echo $value['imagem_usuario'] ?>" alt="" class="fotoperfil">
            <div class="s2">
                <a href="#"> <?php echo $value['nome_usuario'] ?> </a>
                <p><?php echo $value['sobre_usuario'] ?></p>
            </div>
            <div class="s3">
                <?php
                    if($value['email'] == $_SESSION['email']){ ?>
                        <form action="/deletarpostagem" method="post">
                            <input type="hidden" value="<?php echo $value['id'] ?>" name="id">
                            <input class="deletar" type="submit" value="Apagar postagem">
                        </form>
                <?php } else { ?>
                        <button>•••</button>
                <?php } ?>
            </div>
        </div>
        <p class="descricao"> <?php echo $value['descricao'] ?> </p>
        <?php
            if($value['imagem'] != 'sem imagem'){ ?> 
                <img src="../Img/<?php echo $value['imagem'] ?>" alt="Conteudo se tiver">
        <?php } ?>
        <div class="acoes">

                <?php 
                    $caminhocurtir = $value['status_curtida'];
                    $id = $value['id'];

                    if($caminhocurtir === 'curtido') {
                        $caminhocurtir = "/descurtir?postagem=$id";
                        $curtido = 'Não gostei';
                        $classe = 'descurtir';
                    }else {
                        $caminhocurtir = "/curtirPostagem?postagem=$id";
                        $curtido = 'Gostei';
                        $classe = 'curtir';
                    }

                    if(isset($value['local'])) {
                        $caminhocurtir = $caminhocurtir . '&local=perfil';
                    }
                ?>

            <a href=<?php echo $caminhocurtir ?> class= <?php echo $classe ?>><span class="material-symbols-outlined">
                    thumb_up
                </span> <?php echo $curtido ?> </a>
            <button class="comentar"><span class="material-symbols-outlined">
                    comment
                </span> Comentar</button>
        </div>
    </div>
    <hr>
<?php } ?>