<header id="menu">
    <div class="container">
        <h1 id="logomarca">Friend<span>Circle</span></h1>
        <ul>
            <li><a href="/"> <span class="material-symbols-outlined">
                        home
                    </span> Inicio</a></li>
            <li><a href="/perfil"><span class="material-symbols-outlined">
                        person
                    </span>Perfil</a></li>
            <li><a href="/minharede?tip=usuarios"><span class="material-symbols-outlined">
                        group
                    </span>Minha rede</a></li>
        </ul>
        <form action="/minharede?tip=usuarios" method="get">
            <input id="pesquisar_campo" type="text" placeholder="Pesquisar">

            <ul id="pesquisar_lista">
                <li><input type="submit" value="Pesquisar por usuarios"></li>
                <li><input type="submit" value="Pesquisar por grupos"></li>
            </ul>
        </form>
    </div>
</header>