<header id="menu">
    <div class="container">
        <h1 id="logomarca">Friend<span>Circle</span></h1>
        <ul>
            <li><a href="/">Inicio</a></li>
            <li><a href="/perfil">Perfil</a></li>
            <li><a href="#">Minha rede</a></li>
        </ul>
        <form action="" method="get">
            <input type="text" placeholder="Pesquisar">
            <input type="submit" value="pesquisar">
        </form>
    </div>
</header>