<div class="pesquisa">
    <form action="/pesquisar">
        <input type="hidden" name="tip" value='usuarios'>
        <input name="search" type="text">
        <input type="submit" value="Pesquisar">
    </form>
</div>

<div class="resultados">
    <?php
    if(isset($this->view->usuarios)){
        foreach ($this->view->usuarios as $key => $value) { ?>
                <form id="usuario<?php echo $key ?>" class="usuario">
                    <div class="bar">
                        <img src="../img/PerfilVazia.jpg" alt="">
                        <p class="nome"><?php print($value['nome']) ?></p>
                    </div>
                    <p class="sobremim"><?php print($value['sobremim']) ?></p>
                    <input type="submit" value="Pedir para seguir">
                </form>
       <?php }
    }else{
        echo "<h1> Pesquisar por usuarios </h1>";
    }
    ?>
</div>