<div class="pesquisa">
    <form action="/pesquisar">
        <input type="hidden" name="tip" value='usuarios'>
        <input name="search" type="text">
        <input type="submit" value="Pesquisar">
    </form>
</div>

<div class="resultados">
    <?php
    if (isset($this->view->usuarios)) {
        foreach ($this->view->usuarios as $key => $value) { ?>
           
           <?php 
                $action = $value['status_pedido'];
                $id = $value["id"];

                if($action === 'sem_pedido'){
                    $action = "/seguir?usuario=$id";
                }else {
                     $action = "/cancelarPedido?usuario=$id";
                }
            ?>

            <form id="usuario<?php echo $key ?>" class="usuario" action="<?php echo $action ?>" method="post">
                <div class="bar">
                    <img src="../img/<?php echo $value['imagem_usuario'] ?>" alt="">
                    <p class="nome"><?php print($value['nome']) ?></p>
                </div>
                <p class="sobremim"><?php print($value['sobremim']) ?></p>

                <?php if ($value['status_pedido'] === 'sem_pedido') { ?>
                    <input type="submit" value="Pedir para seguir">
                <?php } else { ?>
                    <input type="submit" id="cancelar_s" value="Cancelar a solicitação">
                <?php } ?>

            </form>
    <?php }
    } else {
        echo "<h1> Pesquisar por usuarios </h1>";
    }
    ?>
</div>