<div class="conteudo">
    <div class="informacoes">
        <img src="../img/PerfilVazia.jpg" alt="" class="fotoperfil">
        <div class="s2">
            <a href="#"> <?php $this->show('nome') ?> </a>
            <p>sobre mim</p>
        </div>
        <div class="s3">
            <button>•••</button>
        </div>
    </div>
    <p class="descricao"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas velit
        praesentium quae dolorum nesciunt libero similique rerum eligendi! Neque similique ut
        nesciunt sequi sed, voluptatibus suscipit corporis. Voluptates, harum voluptatem.</p>
    <img src="../img/teste.png" alt="Conteudo se tiver">
    <div class="acoes">
        <button><span class="material-symbols-outlined">
                thumb_up
            </span> Curtir</button>
        <button><span class="material-symbols-outlined">
                comment
            </span> Comentar</button>
    </div>
</div>