<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->layout('LinksHead') ?>
    <title>Rede | FriendCircle</title>
</head>

<body class='minharede'>
    <?php $this->layout('MenuSuperior') ?>
    <main>
        <div class="sec1">
            <div class="outbar">
                <ul>
                    <li><a href="/minharede?tip=usuarios">
                        <span class="material-symbols-outlined">
                                person
                            </span>Pesquisar por usuarios
                    </a></li>
                    <li><a href="/minharede?tip=conexoes">
                        <span class="material-symbols-outlined">
                                group
                            </span>Minhas conexões
                    </a></li>
                    <li><a href="/minharede?tip=solicitacoes">
                        <span class="material-symbols-outlined">
                                group
                            </span>Solicitações de conexão
                    </a></li>
                    <li><a href="/minharede?tip=grupos">
                        <span class="material-symbols-outlined">
                                groups
                            </span>Grupos sociais
                    </a></li>
                </ul>
            </div>
        </div>
        <div class="sec2">
            <?php 
                $tip = $_GET['tip'];
                if(isset($tip)){
                    switch ($tip) {
                        case 'usuarios':
                            $this->layout('PesquisarUsuarios');
                            break;
                        case 'solicitacoes':
                            $this->layout('PesquisarSolicitacoes');
                            break;
                        case 'conexoes':
                            $this->layout('MinhasConexoes');
                            break;
                        case 'grupos':
                            $this->layout('GruposSociais');
                            break;
                        default:
                            echo 'não encontramos';
                            break;
                    }
                }
            ?>
        </div>
    </main>

    <script src="../Js/Eventos.js"></script>
</body>

</html>