<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->layout('LinksHead') ?>
    <title>Perfil | FriendCircle</title>
</head>

<body class="perfil">
    <?php $this->layout('MenuSuperior') ?>
    <main>
        <div class="sec1">
            <?php $this->layout('InformacoesPerfil') ?>

            <div class="exibir_conteudos">
                <?php 
                    $this->layout('ListarPostagens', $this->view->minhas_postagens);
                ?>
            </div>
        </div>

        <div class="sec2">
            <h1>Sugestões para seguir</h1>
            <ul>
                
            </ul>
        </div>
    </main>

    <script src="../Js/Eventos.js"></script>
</body>

</html>