<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->layout('LinksHead') ?>
    <title>Timeline | FriendCircle</title>
</head>

<body class="timeline">
    <div id="loading"></div>
    <?php $this->layout('MenuSuperior') ?>
    <main>
        <div class="container">
            <section class="n1">
                <div class="perfil">
                    <div class="outbar"></div>
                    <div class="fotodeperfil"></div>
                    <a href="#"> <?php $this->show('nome') ?> </a>
                    <p> <?php $this->show('sobremim') ?></p>
                    <ul>
                        <li>Conexões: <span>0</span></li>
                        <li>Postagens: <span>0</span></li>
                        <li>Curtidas: <span>0</span></li>
                    </ul>
                </div>

                <div class="grupos">
                    <p>Grupos seguindo</p>
                    <ul>

                    </ul>
                </div>
            </section>

            <section class="postagem">
                <?php $this->layout('CriarPostagem') ?>

                <div class="classificar">
                    <p>Classificar por: </p>

                    <select name="" id="">
                        <option value="0">Relevantes</option>
                    </select>
                </div>
                <div class="exibir">

                </div>
            </section>
        </div>
    </main>

    <script src="../Js/Eventos.js"></script>
</body>

</html>