<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->layout('LinksHead') ?>
    <title>Timeline | FriendCircle</title>
</head>

<body class="timeline">
    <div id="loading"></div>
    <?php $this->layout('MenuSuperior') ?>
    <main>
        <div class="container">
            <section class="n1">
                <div class="perfil">
                    <div class="outbar"></div>
                    <img src="../img/<?php echo $_SESSION['fotoperfil'] ?>" class="fotodeperfil" alt="">
                    <a href="#"> <?php $this->show('nome') ?> </a>
                    <p> <?php $this->show('sobremim') ?></p>
                    <ul>
                        <li>Conexões: <span><?php echo $this->view->quantidade_usuarios ?></span></li>
                        <li>Postagens: <span><?php echo $this->view->quantidade_postagens ?></span></li>
                        <li>Curtidas: <span><?php echo $this->view->curtidas ?></span></li>
                    </ul>
                </div>

                <div class="grupos">
                    <p>Grupos seguindo</p>
                    <ul>
                        <?php 
                            foreach ($this->view->grupos_seguindo as $key => $value) {
                                $nome = $value['nome_grupo'];
                            ?>

                                <p> <?php echo $nome ?> </p>

                        <?php } ?>
                    </ul>
                </div>

                <a class="logout" href="/sair">Sair da minha conta</a>
            </section>

            <section class="postagem">
                <?php $this->layout('CriarPostagem') ?>

                <div class="classificar">
                    <p>Classificar por: </p>

                    <select name="" id="">
                        <option value="0">Relevantes</option>
                    </select>
                </div>
                <div class="exibir">
                    <?php
                        $this->layout('ListarPostagens', $this->view->timeline);
                    ?>
                </div>
            </section>
        </div>
    </main>

    <script src="../Js/Eventos.js"></script>
</body>

</html>