<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->layout('LinksHead') ?>
    <title>Administrador | FriendCircle</title>
</head>

<body id='admin'>

    <h1>TELA DE CONTROLE DO ADMINISTRADOR</h1>

    <div class="opcoes">
        <ul>
            <li><a href="/">Controle de usuarios</a></li>
            <li><a href="/">Controle de postagens</a></li>
        </ul>

        <a class="sair" href="/sair">Encerrar Seção</a>
    </div>
</body>