<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->layout('LinksHead') ?>
    <title>Administrador | FriendCircle</title>
</head>

<body id='admin'>

    <h1>TELA DE CONTROLE DO ADMINISTRADOR</h1>
 
    <div class="opcoes">
        <ul>
            <li><a href="/adm_usuarios">tb_usuarios</a></li>
            <li><a href="/">tb_postagens</a></li>
            <li><a href="/">tb_comentarios_postagens</a></li>
            <li><a href="/">tb_curtidas_postagens</a></li>
            <li><a href="/">tb_curtidas_comentarios</a></li>
            <li><a href="/">tb_denuncias</a></li>
            <li><a href="/">tb_grupos</a></li>
            <li><a href="/">tb_seguindo_grupos</a></li>
            <li><a href="/">tb_seguidores</a></li>
            <li><a href="/">tb_pedidos_seguidores_pendentes</a></li>
        </ul>

        <a class="sair" href="/sair">Encerrar Seção</a>
    </div>
</body>
</html>
