<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <title>Home | FriendCircle</title>
</head>

<body class="body-registrar">
    <div class="info">
    
        <div class="descricao">
            <h1 id="logomarca">Friend<span>Circle</span></h1>
            <p>
                Junte-se ao FriendCircle para se conectar com a sua gente.
            </p>
            <ul>
                <li> - Conecte-se com seus interesses</li>
                <li> - Fique por dentro de seus interesses</li>
                <li> - Compartilhe Seu Conhecimento e Experiência</li>
                <li> - Crie e Gerencie Seu Próprio Circulo Social</li>
                <li> - Mantenha-se Conectado com Amigos e Colegas</li>
            </ul>
        </div>

    </div>
    <div class="formulario">

        <div style="display: none;" id="autenticar">
            <form class="autenticar" action="/autenticar" method="post">
                <p>Acesse sua conta</p>
                <div class="border">
                    <div class="inputs">
                        <input required type="text" name="email" id="email" placeholder="Digite seu e-mail">
                        <input required type="password" placeholder="Digite sua senha" name="senha" id="senha">
                    </div>
                    <input id="entrar" type="submit" value="Entrar">
                    <a href="#" id="link_autenticar">Não tem uma conta? clique aqui!</a>
                </div>
            </form>
        </div>

        <div style="display: block;" id="registrar">
            <form class="registrar" action="/cadastrar" method="post">
                <p>Crie sua conta</p>
                <div class="border">
                    <div class="inputs">
                        <input required name="nome" type="text" placeholder="Nome de usuario">
                        <input required name="email" type="email" placeholder="Digite seu email">
                        <input required name="senha" type="password" name="senha" id="senha" placeholder="Digite sua senha">
                    </div>
                    
                    <input id="entrar" type="submit" value="Cadastrar">
                    <a href="#" id="link_registrar">Já tem uma conta? clique aqui!</a>
                </div>
            </form>
        </div>
    </div>

    <script src="Js/VerificarCadastro.js"></script>
</body>
</html>